name: Zana Auto Post

on:
  schedule:
    - cron: '0 12 * * *'   # ١٥:٠٠ (٣ی پاشنیوەڕۆ) بە کاتی عێراق
    - cron: '0 13 * * *'   # ١٦:٠٠ (٤ی ئێوارە) بە کاتی عێراق
    - cron: '0 14 * * *'   # ١٧:٠٠ (٥ی ئێوارە) بە کاتی عێراق
    - cron: '0 15 * * *'   # ١٨:٠٠ (٦ی ئێوارە) بە کاتی عێراق
    - cron: '0 16 * * *'   # ١٩:٠٠ (٧ی ئێوارە) بە کاتی عێراق
  workflow_dispatch:       # بۆ کاتی تاقیکردنەوە بە دەست

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pillow gspread google-auth python-telegram-bot requests
      - run: python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
